### ISSUE TITLE
Název pro hlavní postavu

### ISSUE THREAD

**Issue by Dxnxex** [Dxnxex/SpaceEngineersCestina#1]
Astronaut, Inženýr či ponechat Engineer?

**Comment by pa4k** [comment]
za mňa : má to skafander = Astronaut

**Comment by Dxnxex** [comment]
Asi ano 👍

**Comment by Dxnxex** [comment]
Při překladu cítátu či inspirujících vět je Astronaut velice nepřesné v pomyšlení že by se mělo nechat něco jako Inženýř, takže asi hlavní postava bude "Engineer"

**Comment by pa4k** [comment]
Tak potom asi bude fakt najlepšie použiť "Engeneers" ved ta hra je o vesmírnych inžinieroch. A asi to nebude vobec špatné ak sa to ponecha v eng
