### ISSUE TITLE
P-Gravity

### ISSUE THREAD

**Issue by Dxnxex** [Dxnxex/SpaceEngineersCestina#10]
Přeložit jako?

P-Gravitace
Přírodní Gravitace
Přírodní Grav.
Přirozená Gravitace.
Přirozená Grav.

Zkrácení je kvůli délce textu, který pak lícuje přes jinou kolonku či objekt.

**Comment by pa4k** [comment]
Volil by som P-Gravitace (tak je to i v anglictine P-Gravity) a potom A-Gravity = U-Gravitace (ako umělá gravitace)

**Comment by Dxnxex** [comment]
No zatím to nechám otevřené...

**Comment by Dxnxex** [comment]
P-Gravity

**Comment by Dxnxex** [comment]
teda P-Gravitace
