### ISSUE TITLE
Sensor

### ISSUE THREAD

**Issue by Dxnxex** [Dxnxex/SpaceEngineersCestina#12]
Je lepší Senzor nebo Snímač?

**Comment by pa4k** [comment]
Mno, ako kde ale v rámci tejto hry asi Senzor.
Lebo máš napr. Dverovy senzor, ale zas na druhú stranu, snímač pohybu. A tie senzory v hre vlastne reagujú na pohyb.
Ale za mňa senzor je taký všeobecnejší vyraz.
