### ISSUE TITLE
Odriadkovanie

### ISSUE THREAD

**Issue by pa4k** [Dxnxex/SpaceEngineersCestina#14]
mám taký pocit, že ten tvoj program ti nezachováva odriadkovanie.
Pozri na ID: BlockPropertyDescription_Motor_SuspensionTravel

ty máš text na jednom riadku: 

`<value>Limits the suspension's travel height.Setting to 0% will effectively lock the suspension.</value>`

ale originál v ENG verzii súboru to je takto:

```
<value>Limits the suspension's travel height.
Setting to 0% will effectively lock the suspension.</value>
```

**Comment by Dxnxex** [comment]
Vím no dělal jsem ho 😁


EDIT: Budu asi řešit jinak... nechce se mně upravovat program aby hledal ještě další řádky

**Comment by pa4k** [comment]
Ak som si to spravne vsimol tak znakom toho ze tam ma byt enter he ze po konci vety za tečkou neni mezera. A pokračuje rovno dalsia veta

**Comment by Dxnxex** [comment]
To úplně není pravda si myslím.
Fakt nevím ale myslím si že tam někde je tečka na konci ale pokračuje dalším řádkem...

Jak říkám toto bych neřešil...
To jsou pak korekce, které jsou potřeba vidět, aby to dobře vypadalo. To se pak může (spíše by i mělo) udělat ručně.

Příklad:

Strašně dlouhý text, který mám rád, ale používá náboje 330 mm ke zničení krátkých vět.

Bych poté spíše dal a přepsal:

Strašně dlouhý text, který mám rád. Ničí krátké věty.
Náboje: 330 mm

+To můžu myslím udělat nějakou barvou..
