### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by pa4k** [Dxnxex/SpaceEngineersCestina#17]
ako prekladať pojem Grid?
používam konstrukce ale príde mi to voči pôvodnému eng slovu trochu dlhé, takže netuším či to niekde nebude kolidovať s niečim.
Otázka je či existuje lepšia adekvátna náhrada. Rošt, síť, mřížka mi neprídu úplne ideálne.

**Comment by Dxnxex** [comment]
Grid jako loď je konstrukce...
jinak mřížka co se týče nějakého stavění

**Comment by pa4k** [comment]
A co tak to sjednotit jako: struktura

Pouzitelné pro loď i jakoukoliv stavbu.
