### ISSUE TITLE
Willis Duct

### ISSUE THREAD

**Issue by Dxnxex** [Dxnxex/SpaceEngineersCestina#2]
Může to být jako Průchod?

**Comment by pa4k** [comment]
a čo tak šachta

**Comment by Dxnxex** [comment]
Možná...

**Comment by Dxnxex** [comment]
Jelikož je to v IDčku jako AirDuct což je Ventilace či volné přeložení "průchod pro vzduch" Šachtu si spíše představují jako něco vykopaného.
Maximálně Ventilace... ale to bych bral spíše jako zařízení

**Comment by pa4k** [comment]
predpokladám ale že sa v tom bude dať aj pohybovať (aspoň čo som na to pozeral) takže v takom prípade sa úplne hodí napr. "ventilační / vetrací šachta"

**Comment by Dxnxex** [comment]
Nevím 2 slova .. no uvidím :)

**Comment by pa4k** [comment]
aj v ENG su to dve slová

**Comment by Dxnxex** [comment]
OK

Příště bude předelano na Větrací šachta.
