### ISSUE TITLE
Armor - Tip

### ISSUE THREAD

**Issue by Dxnxex** [Dxnxex/SpaceEngineersCestina#5]
Špička - Špice

**Comment by Dxnxex** [comment]
Opravit -- Zkošené na Zkosené .. omlouvám se .. :D

**Comment by pa4k** [comment]
pozerám že Blueprint prekladáš ako plánky ja by som to nechal ako Blueprinty (tomu každy rozumie) možno ešte "plány" alebo "výkresy"

tu ti chýba na konci ukončujúca hranatá závorka:
```
<data name="BlockAction_RemoveFromToolbar" xml:space="preserve">
<value>[odebrat z nástrojového panelu</value>
```

ďalej máš tam:
```
<data name="BlockPropertyTitle_BreakForce" xml:space="preserve">
<value>Síla zlomu</value>
```

čo súvisí s 
```
<data name="BlockPropertyDescription_BreakForce" xml:space="preserve">
<value>Podvozek se automaticky odemkne pokud vyvinutá síla, která drží podvozek přichycený je vyšší jako tato hodnota</value>
```
takže by to nemala byť "Síla zlomu" ale "Síla oddelení" prípadne "Síla rozpojení"

A možno ešte tu:
```
<data name="BroadcastScreen_TerminalButtonDisabled_ToolTip" xml:space="preserve">
<value>Nemohu otevřít termínál cílené konstrukce. Přejeď myší přes ikonu stavu pro více informací.</value>
```
slovo "cílené" nahradiť "cílové"

**Comment by pa4k** [comment]
Našiel som ešte nejaké chyby:

```
<data name="FlightMovementBlock_NoThrustInAllDirections" xml:space="preserve">
<value>[Color=#FFFF0000]CHYBA: Konstrukce se nemůže pohybovat jedním nebo více směry, zajistěte, aby byl pro každý směr k dispozici tryska!</value>
```

na konci druhero riadku za slovom tryska!  máš odmazanu ukončovaciu značku pre farbu textu: `[/Color]`



Tu ti chýba "s" v slove "vlatněn"
```
<data name="StoreSell_Error_Text_NoFaction" xml:space="preserve">
<value>Obchod není vlatněn klanem.</value>
```
ale asi by som to preformuloval nasledovne: "Obchod není ve vlastnictví klanu."

**Comment by pa4k** [comment]
P-Gravity - prekladáš ako přírodní gravitace, osobne by som to nechal ako P-Gravitace, prípadne prirozená gravitace.

napr. tu:
```
<data name="FlightMovementBlock_MaxRollAngle_Tooltip" xml:space="preserve">
<value>Při přesunu k bodu trasy v přírodní gravitaci se může konstrukce přetočit doleva nebo doprava o tento úhel</value>
```

osobne by som to preložil nasledovne:
```
<data name="FlightMovementBlock_MaxRollAngle_Tooltip" xml:space="preserve">
<value>Při přesunu k bodu trasy v systému P-Gravitace se může konstrukce přetočit doleva nebo doprava o tento úhel</value>
```

**Comment by Dxnxex** [comment]
Pár věcí jsem upravil.

Ale pár věcí je na rozhodnutí.

Děkuji

**Comment by Dxnxex** [comment]
Síla zlomu nevím :/

**Comment by pa4k** [comment]
> Síla zlomu nevím :/

hm no to asi nie ale ide tu o to že akú silu musíš vyvinúť aby si sa odpútal.
ja som ti tam písal návrhy: Síla oddelení" prípadne "Síla rozpojení"
