### ISSUE TITLE
Assembler - Pár pripomienok - pa4k

### ISSUE THREAD

**Issue by pa4k** [Dxnxex/SpaceEngineersCestina#6]
Survival kit - Základní modul - asi by som to nazval: Modul přežití nebo Sada/Modul pro přežití
Assembler - buď nechať ako počeštený: Asemblér alebo Konstruktér prípadne Sestavovač

**Comment by Dxnxex** [comment]
Survival kit - Modul přežití je divné a nechci to mít tak dlouhé aby tam bylo to "pro" přežití.
Assembler - Ještě jsem přemýšlel nad "Výrobník", "Výrobní linka", "Montovač" či "Konstruktér" .. ale zatím nechám Montér... zatím.

**Comment by pa4k** [comment]
Assembler  - ok "Výrobník" a "Konstruktér" znejú fajn u mňa slovo Montér evokuje týpka s hasákom v ruke :)

**Comment by Dxnxex** [comment]
Bohužel změna bude v další verzi :/

**Comment by pa4k** [comment]
a čo "Sestavovač"?
