### ISSUE TITLE
Panely

### ISSUE THREAD

**Issue by Dxnxex** [Dxnxex/SpaceEngineersCestina#9]
Máme dva druhy panelů... na kterém jsou tlačítka a na kterém je ta modrá obrazovka (Ovládací panel)

Momentálně to chci sjednotit a udělat vždy významově stejný začátek. 
 Příklad jiného typu: Vodíková trysky, Atmosférická trysky (i když tyty takto měnit nebudu)
 Výsledek: Trysky - Vodíková | Trysky - Atmosférická

Teď mám:

Panel - Tlačítkový - ***
Panel - Ovládací - ***

Místo toho panelu přemýšlím třeba: "Ovládání", "Konzole" či "Počítač"

PS. Ve vývojové verzi je to zatím pojmenováno jako "XPanel"

**Comment by pa4k** [comment]
>Výsledek: Trysky - Vodíková | Trysky - 
 Atmosférická

Nebolo by lepšie:
Trysky - Vodíkove | Trysky - Atmosférické

>Místo toho panelu přemýšlím třeba: "Ovládání", "Konzole" či "Počítač"

Tu mi najviac sedí "Konzole"

**Comment by Dxnxex** [comment]
Konzole tím pádem to bude
